Mobile menu
Gardimy/Application-deploy pull request #4
Opened 2023-02-05 01:12 UTC by Gardimy

In this project, I use JavaScript to  implement the following features:

1) When the user clicks (or taps) the hamburger button, the mobile menu appears.
2) When the user clicks (or taps) the close (X) button, the mobile menu disappears.
3) When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
4) When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

2023-02-06 19:01 UTC, huseyinbiyik requested changes
Hi @Gardimy and @danielochuba 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Nav-bar functionalities work just fine 👌
- Collaborative work 😎😎
- Github flow followed 👌
- Commit messages are meaningful and written in imperative tense 📝
- PR description is descriptive 📝

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-06 19:01 UTC, huseyinbiyik commented on gdm.js
> +const menu = document.querySelector('.mobile-menu');
[OPTIONAL] The general practice for the naming of JavaScript files based on what they consist of, or the functionality of that file. Instead of gdm.js, I think index.js or navbar.js would be a better naming. 👍

2023-02-06 19:01 UTC, huseyinbiyik commented on Style.css
> +.closeIcon {
Close button works fine 👌 But let's follow the Figma template and use the same icon instead of test "close". 👍
<img width="388" alt="Screenshot 2023-02-06 at 9 49 19 PM" src="https://user-images.githubusercontent.com/25887253/217059046-27232078-ad04-4e72-9d96-45a8784cc059.png">
<img width="388" alt="Screenshot 2023-02-06 at 9 49 32 PM" src="https://user-images.githubusercontent.com/25887253/217059048-528e110b-e40b-479f-9b1c-e367cfdc1e8e.png">

2023-02-06 19:01 UTC, huseyinbiyik commented on Style.css
> +.menuIcon {
Great job with the functionality, it works perfectly 😎 But let's stick with the Figma template and add hamburger icon for the mobile nav like below.
<img width="500" alt="Screenshot 2023-02-06 at 9 37 00 PM" src="https://user-images.githubusercontent.com/25887253/217058618-328d3893-710d-41be-9212-44184d3b3e6e.png">


Yours:
<img width="388" alt="Screenshot 2023-02-06 at 9 46 28 PM" src="https://user-images.githubusercontent.com/25887253/217058372-c60c5568-4ab7-4fd5-bdb1-4680f9ce568f.png">

2023-02-06 19:01 UTC, huseyinbiyik commented on Style.css
> +.mobile-menu {
Brilliant job with the font family, size and weight 👨‍🎨 But let's fix the left-padding to match the Figma template. 🦾
<img width="388" alt="Screenshot 2023-02-06 at 9 49 00 PM" src="https://user-images.githubusercontent.com/25887253/217059767-63246e8f-300b-4922-9d3c-6bf4c9ef3028.png">

2023-02-06 19:01 UTC, huseyinbiyik commented on README.md
> +# Porfolio: Mobile-menu
Kindly remove the placeholder texts below. And please make sure your license link in your license section works fine. Currently, it gives 404.
<img width="500" alt="Screenshot 2023-02-06 at 9 38 13 PM" src="https://user-images.githubusercontent.com/25887253/217060303-d5526615-a016-45a7-b2a3-686719a71800.png">

<img width="796" alt="Screenshot 2023-02-06 at 9 39 09 PM" src="https://user-images.githubusercontent.com/25887253/217060016-8a42352d-1996-4c65-99bc-786bb86324b2.png">

2023-02-06 19:01 UTC, huseyinbiyik commented on .github/workflows/linters.yml
> +name: Linters
Great job with adding the correct linters. But let's remove the old file. There is another file called ! linters.yml. Kindly remove that one. 🗡️

2023-02-06 23:15 UTC, t-yanick requested changes
Hi @Gardimy , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-06 23:15 UTC, t-yanick commented on README.md
>    <h3><b>Microverse README Template</b></h3>
- [ ] As inidicated by the previous reviewer, kindly remove placeholder text. This include the Default title Microverse ReadMe Template. Remeber the objective is to personalize the ReadMe. 
![Screen Shot 2023-02-06 at 3 12 40 PM](https://user-images.githubusercontent.com/62849872/217108414-e94d1273-3187-4604-9197-675f08edbe96.png)

2023-02-06 23:43 UTC, Reem-lab reviewed
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional README since you removed the table of the content so please see my comment below ⬇💯💯

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-06 23:43 UTC, Reem-lab commented on README.md
> -
Great hob so far but I think you removed the table of content in your README but you shouldn't remove it,
I think you missunderstood the previous code reviewer so he was asking for changing the logo title and put you own logo or project logo! so kindly add it again! ✅💯🔥🙏🏻🙏🏻

2023-02-07 00:34 UTC, KanzaTahreem approved these changes
# Approved 🥳

Hi team 👋

Great work nailing the milestone. I would like to express my deep appreciation for the time and effort you dedicated to this project 💪

**_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Collaborative work
-  ✅ Great work using the right GitHub Flow 
-  ✅ Commits are descriptive, good work.
-  ✅ Linters are working properly, great job! 

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Excellent work implementing the changes 👍 How about fixing the link for LICENSE file as well? Right now, I'm getting the following error when I'm clicking on the link 🔗 We don't want our user to experience the same thing, Right? 🎯 I know you can fix this 💪
![image](https://user-images.githubusercontent.com/106119105/217117770-38a2b75b-9834-4424-b07c-a5bfeac2cf3d.png)

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-07 13:47 UTC, merged